### ISSUE TITLE
Unclear how the u-root argv override works 

### ISSUE THREAD

**Issue by bjoto** [system-transparency/system-transparency#166] opened 2022-03-09 18:01 UTC
Previously, passing `uroot.uinitargs` to the kernel command line made stboot pick up this exact cmdline argument.

Now, it's the buildsystem passes HOST_CONFIG_ARG and ST_STBOOT_ARGS to the command line, which has precedence over the kernel command line.

This is poorly documented. :-(

**Comment by sylv-io** [comment] 2022-03-10 11:19
My bad, we have merged the last PR #160 without adapting the documentation :/ 
Adapting the request #154 changed this behavior. Let me check if we could support both ways of setting stboot args and update the documentation.

**Comment by sylv-io** [comment] 2022-03-14 14:32
It looks like migrating the GNU Make Linux kernel to taskfile introduced a regression with a silent error...
PR #160 should fix this issue.
In addition, I added a precondition to prevent defining stboot args via config and kernel parameter simultaneous.

**Comment by sylv-io** [comment] 2022-06-02 14:45
#168 fixed the regression and updated the documentation accordantly.

**Closed by sylv-io** 2022-06-02 14:45 UTC
